### ISSUE TITLE
Red and blue reversed

### ISSUE THREAD

**Issue by amadensor** [dmitri-mcguckin/octoprint-stuff#1]
The image swaps red and blue.

**Comment by amadensor** [comment]
Digging in, I see that the image comes directly from opencv.   Now digging into those modules trying to see how it is built so I can find the fix.   Might be a param passed on init, might be a webcamd bug.  Still searching.

**Comment by amadensor** [comment]
Found the fix!   PR inbound.

**Comment by dmitri-mcguckin** [comment]
Issue closed with PR #2
