### ISSUE TITLE
Upstream Attribution

### ISSUE THREAD

**Issue by christopherkobayashi** [dmitri-mcguckin/octoprint-stuff#3]
Hello Dmitri,

First off, thanks for adding the bits that allow webcam.py to be installed via pip.  That is a very useful feature.

However ... I couldn't help but notice that you (undoubtably accidentally) removed the code attribution from the top of the original webcam.py for both myself and Igor.

A quick diff between your __main__.py and my webcam.py indicates that the differences are primarily cosmetic whitespace changes.

Would you mind restoring the authorship credit to the relevant files?  As this code is licensed under GPL-3.0, retaining attribution (no matter how little original code is retained) is generally considered to be good manners.

Thank you very much in advance, and cheers,

-- Chris

**Comment by dmitri-mcguckin** [comment]
Hey Chris,

No worries.

I tend to prefer putting attributes in places such as LICENSES.txt or something like that. Would that be amenable to you guys?

I try to avoid putting license details directly in source files since those files are often subject to change, and it's been a while since I looked at your original copy but I did remove the original webcam.py and split up the original behavior into a submodule structure. It does appear I also attributed you guys in the [README](https://github.com/dmitri-mcguckin/webcamd/blob/master/README.md). 

Do let me know your thoughts.

All the best.

**Comment by dmitri-mcguckin** [comment]
Just to correct a small bit of what you said.

Per the GPLv3 license I am not required to attribute the specific authors of previous derivatives or upstream copies.

In-fact the license actually discusses the opposite effect to that: erroneous attribution regarding changes that the upstream authors did not make.

See `part (i)`:

```
  For the developers' and authors' protection, the GPL clearly explains
that there is no warranty for this free software.  For both users' and
authors' sake, the GPL requires that modified versions be marked as
changed, so that their problems will not be attributed erroneously to
authors of previous versions.
```

&nbsp;

Now that said, I am more than willing to give credit where credit is due. Please let me know what compromise is acceptable to you.

&nbsp;

That said, my obligations to the license are to propagate the same GPLv3 license and mark this software as changed. Which has been done within reason.

**Comment by christopherkobayashi** [comment]
Hello Dmitri,

Thank you for getting back to me on this issue.

Restoring attribution to what became webcamd/__main__.py like this:

```
# Original author: Igor Maculan <n3wtron@gmail.com>
#
# Fixes by Christopher RYU <software-github@disavowed.jp>
```

... would be both appropriate and acceptable.

Cheers,

-- Chris

**Comment by dmitri-mcguckin** [comment]
Hey Chris,

Would it be ok if I put that either in CONTRIBUTORS.md or the README.md instead?

I prefer to keep any kind of explicit licensing or authorship details out of source files since those tend to change a lot.

**Comment by christopherkobayashi** [comment]
README.md would be fine.

**Comment by christopherkobayashi** [comment]
Hello Dmitri,

I see that you closed this, but you haven't actually modified anything.  Was this an oversight?

Cheers,

Chris
